# Generated by Django 3.1.2 on 2020-10-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_orders_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image4',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image5',
            field=models.ImageField(null=True, upload_to='shop/images'),
        ),
    ]
